/* Formatted on 14/10/2015 20:34:28 (QP5 v5.252.13127.32867) */
SET TERMOUT OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF



COLUMN POR_REVISAR HEADING "POR_REVISAR" FORMAT A10  TRUNC  NEW_VALUE V_POR_REVISAR

SELECT COUNT (*) POR_REVISAR
  FROM (  SELECT V_PRACTICAS_GESTION.ID,
                 V_PRACTICAS_GESTION.NOMBRE,
                 V_PRACTICAS_GESTION.CODIFICACION,
                 V_PRACTICAS_GESTION.DESCRIPCION,
                 V_PRACTICAS_GESTION.SIGLAS_PROCESO,
                 V_PRACTICAS_GESTION.PROCESO,
                 V_PRACTICAS_GESTION.DESCRIPCION_PROCESO,
                 V_PRACTICAS_GESTION.DECLARACION_PROPOSITO,
                 V_PRACTICAS_GESTION.PRACTICAS_SIGLAS,
                 V_PRACTICAS_GESTION.PRACTICA_GESTION,
                 V_PRACTICAS_GESTION.ORDEN_ACTIVIDAD,
                 V_PRACTICAS_GESTION.ACTIVIDAD,
                 V_PRACTICAS_GESTION.EVIDENCIAS_ENCONTRADAS,
                 V_PRACTICAS_GESTION.EVIDENCIAS_EVALUADAS,
                 V_PRACTICAS_GESTION.REVISADO
            FROM M10.V_PRACTICAS_GESTION
           WHERE V_PRACTICAS_GESTION.REVISADO = 0
        ORDER BY V_PRACTICAS_GESTION.PRACTICAS_SIGLAS);



COLUMN ID FORMAT A20 TRUNC NEW_VALUE V_ID
COLUMN NOMBRE FORMAT A20 TRUNC NEW_VALUE V_NOMBRE
COLUMN CODIFICACION FORMAT A20 TRUNC NEW_VALUE V_CODIFICACION
COLUMN DESCRIPCION FORMAT A20 TRUNC NEW_VALUE V_DESCRIPCION
COLUMN SIGLAS_PROCESO FORMAT A20 TRUNC NEW_VALUE V_SIGLAS_PROCESO
COLUMN PROCESO FORMAT A100 TRUNC NEW_VALUE V_PROCESO
COLUMN DESCRIPCION_PROCESO FORMAT A20 TRUNC NEW_VALUE V_DESCRIPCION_PROCESO
COLUMN DECLARACION_PROPOSITO FORMAT A20 TRUNC NEW_VALUE V_DECLARACION_PROPOSITO
COLUMN PRACTICAS_SIGLAS FORMAT A20 TRUNC NEW_VALUE V_PRACTICAS_SIGLAS
COLUMN PRACTICA_GESTION FORMAT A20 TRUNC NEW_VALUE V_PRACTICA_GESTION
COLUMN ORDEN_ACTIVIDAD FORMAT A20 TRUNC NEW_VALUE V_ORDEN_ACTIVIDAD
COLUMN ACTIVIDAD FORMAT A20 TRUNC NEW_VALUE V_ACTIVIDAD
COLUMN EVIDENCIAS_ENCONTRADAS FORMAT A20 TRUNC NEW_VALUE V_EVIDENCIAS_ENCONTRADAS
COLUMN EVIDENCIAS_EVALUADAS FORMAT A20 TRUNC NEW_VALUE V_EVIDENCIAS_EVALUADAS
COLUMN REVISADO FORMAT A20 TRUNC NEW_VALUE V_REVISADO

SELECT *
  FROM (  SELECT V_PRACTICAS_GESTION.ID,
                 V_PRACTICAS_GESTION.NOMBRE,
                 V_PRACTICAS_GESTION.CODIFICACION,
                 V_PRACTICAS_GESTION.DESCRIPCION,
                 V_PRACTICAS_GESTION.SIGLAS_PROCESO,
                 V_PRACTICAS_GESTION.PROCESO,
                 V_PRACTICAS_GESTION.DESCRIPCION_PROCESO,
                 V_PRACTICAS_GESTION.DECLARACION_PROPOSITO,
                 V_PRACTICAS_GESTION.PRACTICAS_SIGLAS,
                 V_PRACTICAS_GESTION.PRACTICA_GESTION,
                 V_PRACTICAS_GESTION.ORDEN_ACTIVIDAD,
                 V_PRACTICAS_GESTION.ACTIVIDAD,
                 V_PRACTICAS_GESTION.EVIDENCIAS_ENCONTRADAS,
                 V_PRACTICAS_GESTION.EVIDENCIAS_EVALUADAS,
                 V_PRACTICAS_GESTION.REVISADO
            FROM M10.V_PRACTICAS_GESTION
        ORDER BY V_PRACTICAS_GESTION.PRACTICAS_SIGLAS)
 WHERE ROWNUM = 1;


SET TERMOUT ON
PAUSE FALTAN POR REVISAR &&V_POR_REVISAR ACTIVIDADES
PAUSE LA ORGANIZACIÓN ES "&&V_NOMBRE"
PAUSE EL DOMINIIO "&&V_DESCRIPCION" DE CODIGO: "&&V_CODIFICACION"
PAUSE DE PROCESO SIGLAS "&&V_SIGLAS_PROCESO"
PAUSE DE PROCESO: "&&V_PROCESO"
PAUSE DETALLE DE PROCESO: "&&V_DESCRIPCION_PROCESO"
PAUSE EL PROPOSITO DEL MISMO "&&V_DECLARACION_PROPOSITO"
PAUSE DE PRACTICA DE GESTION "&&V_PRACTICAS_SIGLAS": "&&V_PRACTICA_GESTION"
PAUSE LA ACTIVIDAD QUE SE VA A VALORAR ES  "&&V_ORDEN_ACTIVIDAD..&&V_ACTIVIDAD."


UPDATE M10.COBIT_06_EVALUACION
   SET COBIT_06_EVALUACION.EVIDENCIAS_ENCONTRADAS = '&&VEVIDENCIAS_ENCONTR'
 WHERE COBIT_06_EVALUACION.ID = '&&V_ID';

PAUSE LA ACTIVIDAD QUE SE VA A VALORAR ES  "&&V_ORDEN_ACTIVIDAD..&&V_ACTIVIDAD."

UPDATE M10.COBIT_06_EVALUACION
   SET COBIT_06_EVALUACION.EVIDENCIAS_EVALUADAS = '&&V_EVID_EVALUADAS'
 WHERE COBIT_06_EVALUACION.ID = '&&V_ID';


BEGIN
   IF TRIM (UPPER ('&&GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/